name: Check
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Install deps
      run: pip install --no-cache-dir -r requirements.txt